// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/bborbe/alert/k8s/apis/monitoring.benjamin-borbe.de/v1"
	monitoringbenjaminborbedev1 "github.com/bborbe/alert/k8s/client/applyconfiguration/monitoring.benjamin-borbe.de/v1"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=monitoring, Version=v1
	case v1.SchemeGroupVersion.WithKind("Alert"):
		return &monitoringbenjaminborbedev1.AlertApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("AlertSpec"):
		return &monitoringbenjaminborbedev1.AlertSpecApplyConfiguration{}

	}
	return nil
}
