// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1 "github.com/bborbe/alert/k8s/apis/monitoring.benjamin-borbe.de/v1"
	monitoringbenjaminborbedev1 "github.com/bborbe/alert/k8s/client/applyconfiguration/monitoring.benjamin-borbe.de/v1"
	scheme "github.com/bborbe/alert/k8s/client/clientset/versioned/scheme"
)

// AlertsGetter has a method to return a AlertInterface.
// A group's client should implement this interface.
type AlertsGetter interface {
	Alerts(namespace string) AlertInterface
}

// AlertInterface has methods to work with Alert resources.
type AlertInterface interface {
	Create(ctx context.Context, alert *v1.Alert, opts metav1.CreateOptions) (*v1.Alert, error)
	Update(ctx context.Context, alert *v1.Alert, opts metav1.UpdateOptions) (*v1.Alert, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Alert, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AlertList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Alert, err error)
	Apply(ctx context.Context, alert *monitoringbenjaminborbedev1.AlertApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Alert, err error)
	AlertExpansion
}

// alerts implements AlertInterface
type alerts struct {
	client rest.Interface
	ns     string
}

// newAlerts returns a Alerts
func newAlerts(c *MonitoringV1Client, namespace string) *alerts {
	return &alerts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the alert, and returns the corresponding alert object, and an error if there is any.
func (c *alerts) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Alert, err error) {
	result = &v1.Alert{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alerts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Alerts that match those selectors.
func (c *alerts) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AlertList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AlertList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested alerts.
func (c *alerts) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("alerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a alert and creates it.  Returns the server's representation of the alert, and an error, if there is any.
func (c *alerts) Create(ctx context.Context, alert *v1.Alert, opts metav1.CreateOptions) (result *v1.Alert, err error) {
	result = &v1.Alert{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("alerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(alert).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a alert and updates it. Returns the server's representation of the alert, and an error, if there is any.
func (c *alerts) Update(ctx context.Context, alert *v1.Alert, opts metav1.UpdateOptions) (result *v1.Alert, err error) {
	result = &v1.Alert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("alerts").
		Name(alert.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(alert).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the alert and deletes it. Returns an error if one occurs.
func (c *alerts) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alerts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *alerts) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alerts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched alert.
func (c *alerts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Alert, err error) {
	result = &v1.Alert{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("alerts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied alert.
func (c *alerts) Apply(ctx context.Context, alert *monitoringbenjaminborbedev1.AlertApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Alert, err error) {
	if alert == nil {
		return nil, fmt.Errorf("alert provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(alert)
	if err != nil {
		return nil, err
	}
	name := alert.Name
	if name == nil {
		return nil, fmt.Errorf("alert.Name must be provided to Apply")
	}
	result = &v1.Alert{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("alerts").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
