// Copyright (c) 2025 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	monitoringbenjaminborbedev1 "github.com/bborbe/alert/k8s/apis/monitoring.benjamin-borbe.de/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AlertLister helps list Alerts.
// All objects returned here must be treated as read-only.
type AlertLister interface {
	// List lists all Alerts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*monitoringbenjaminborbedev1.Alert, err error)
	// Alerts returns an object that can list and get Alerts.
	Alerts(namespace string) AlertNamespaceLister
	AlertListerExpansion
}

// alertLister implements the AlertLister interface.
type alertLister struct {
	listers.ResourceIndexer[*monitoringbenjaminborbedev1.Alert]
}

// NewAlertLister returns a new AlertLister.
func NewAlertLister(indexer cache.Indexer) AlertLister {
	return &alertLister{listers.New[*monitoringbenjaminborbedev1.Alert](indexer, monitoringbenjaminborbedev1.Resource("alert"))}
}

// Alerts returns an object that can list and get Alerts.
func (s *alertLister) Alerts(namespace string) AlertNamespaceLister {
	return alertNamespaceLister{listers.NewNamespaced[*monitoringbenjaminborbedev1.Alert](s.ResourceIndexer, namespace)}
}

// AlertNamespaceLister helps list and get Alerts.
// All objects returned here must be treated as read-only.
type AlertNamespaceLister interface {
	// List lists all Alerts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*monitoringbenjaminborbedev1.Alert, err error)
	// Get retrieves the Alert from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*monitoringbenjaminborbedev1.Alert, error)
	AlertNamespaceListerExpansion
}

// alertNamespaceLister implements the AlertNamespaceLister
// interface.
type alertNamespaceLister struct {
	listers.ResourceIndexer[*monitoringbenjaminborbedev1.Alert]
}
