// Copyright (c) 2024 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AlertListerExpansion allows custom methods to be added to
// AlertLister.
type AlertListerExpansion interface{}

// AlertNamespaceListerExpansion allows custom methods to be added to
// AlertNamespaceLister.
type AlertNamespaceListerExpansion interface{}
